//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A_projekt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A_projekt.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemůžete uložit nic, první vyhledejte nějaké údaje..
        /// </summary>
        internal static string cantSaveNothing {
            get {
                return ResourceManager.GetString("cantSaveNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název města.
        /// </summary>
        internal static string cityName {
            get {
                return ResourceManager.GetString("cityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Město nebylo nalezeno.
        /// </summary>
        internal static string cityNotFound {
            get {
                return ResourceManager.GetString("cityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najdi.
        /// </summary>
        internal static string find {
            get {
                return ResourceManager.GetString("find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidita.
        /// </summary>
        internal static string humidity {
            get {
                return ResourceManager.GetString("humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načti.
        /// </summary>
        internal static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nějaký plugin byl přidán restartujte program aby jste viděli aktualní data..
        /// </summary>
        internal static string pluginAdded {
            get {
                return ResourceManager.GetString("pluginAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nějaký plugin byl smazán restartujte program aby jste viděli aktualní data..
        /// </summary>
        internal static string pluginDeleted {
            get {
                return ResourceManager.GetString("pluginDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulož.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data byly úspěšně uložena..
        /// </summary>
        internal static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdroj nebyl vybrán, prosím vyberte nějaký zdroj..
        /// </summary>
        internal static string sourceNotChosen {
            get {
                return ResourceManager.GetString("sourceNotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teplota.
        /// </summary>
        internal static string temperature {
            get {
                return ResourceManager.GetString("temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte město přesněji..
        /// </summary>
        internal static string typeCityNameCorrectly {
            get {
                return ResourceManager.GetString("typeCityNameCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rychlost větru.
        /// </summary>
        internal static string windSpeed {
            get {
                return ResourceManager.GetString("windSpeed", resourceCulture);
            }
        }
    }
}
